lib: [
  "_build/install/default/lib/assignment1/META"
  "_build/install/default/lib/assignment1/assignment1.a"
  "_build/install/default/lib/assignment1/assignment1.cma"
  "_build/install/default/lib/assignment1/assignment1.cmi"
  "_build/install/default/lib/assignment1/assignment1.cmt"
  "_build/install/default/lib/assignment1/assignment1.cmx"
  "_build/install/default/lib/assignment1/assignment1.cmxa"
  "_build/install/default/lib/assignment1/assignment1.ml"
  "_build/install/default/lib/assignment1/assignment1__Quiz.cmi"
  "_build/install/default/lib/assignment1/assignment1__Quiz.cmt"
  "_build/install/default/lib/assignment1/assignment1__Quiz.cmx"
  "_build/install/default/lib/assignment1/assignment1__Vector.cmi"
  "_build/install/default/lib/assignment1/assignment1__Vector.cmt"
  "_build/install/default/lib/assignment1/assignment1__Vector.cmti"
  "_build/install/default/lib/assignment1/assignment1__Vector.cmx"
  "_build/install/default/lib/assignment1/dune-package"
  "_build/install/default/lib/assignment1/opam"
  "_build/install/default/lib/assignment1/quiz.ml"
  "_build/install/default/lib/assignment1/vector.ml"
  "_build/install/default/lib/assignment1/vector.mli"
]
libexec: [
  "_build/install/default/lib/assignment1/assignment1.cmxs"
]
bin: [
  "_build/install/default/bin/assignment1.exe"
]
